### ISSUE TITLE
Channel number is off by one

### ISSUE THREAD

**Issue by Barabas5532** [craigsapp/midifile#106]
From the MIDI 1.0 Detailed Specification version 4.2.1, Table 1, Note On STATUS byte is encoded as `1001nnnn`
> `nnnn`: N-1, where N = Channel #,
i.e. 0000 is Channel 1, 0001 is Channel 2,

The makeNoteOn function implementation is off by one, setting the channel to 1 actually creates a message on channel 2. Setting the channel to 16 overflows to channel 1. This is quite confusing, and should be documented for functions that operate on the channel.

```
void MidiMessage::makeNoteOn(int channel, int key, int velocity) {
	resize(3);
	(*this)[0] = 0x90 | (0x0f & channel);
	(*this)[1] = key & 0x7f;
	(*this)[2] = velocity & 0x7f;
}
```

**Comment by craigsapp** [comment]
The channel variable is assumed to be 0-indexed, not 1-index.   So there is no problem in the code.  If your channel variable is 1-index, then subtract one when using it with the midifile library (which does not do any 1-indexing).

The comment just above the quoted code somewhat explicitly describes this, since the default value of channel is 0 (not 1):

```cpp
//////////////////////////////
//
// MidiMessage::makeNoteOn -- create a note-on message.
//
// default value: channel = 0
//
// Note: The channel parameter used to be last, but makes more sense to
//   have it first...
//
```

**Comment by wherefree** [comment]
您好，您所发送的邮件我已收到。

**Comment by craigsapp** [comment]
> 您好，您所发送的邮件我已收到。

很高兴你收到了我的电子邮件。 但是，您不应该自动回复 github 问题。否则我最终可能会禁止你。
