### ISSUE TITLE
2 Indexing Errors, already fixed them. 

### ISSUE THREAD

**Issue by JThatcher2016** [craigsapp/midifile#13]
I found two indexing errors in joinTracks(); and splitTracks();, both errors involved going out of bounds on the vector, I already fixed the errors after some reading up on the documentation for vectors, and will leave the updated MidiFile.cpp attached to this ticket. Note the commenting for info.

[MidiFile.cpp.zip](https://github.com/craigsapp/midifile/files/119115/MidiFile.cpp.zip)

**Comment by craigsapp** [comment]
The function MidiFile::clear_no_deallocate() seems to be the real problem being caused in joinTracks().  The last line in clear_no_deallocate() causes a small memory leak:

```
void MidiFile::clear_no_deallocate(void) {
   for (int i=0; i<getTrackCount(); i++) {
      events[i]->detach();
      delete events[i];
      events[i] = NULL;
   }
   events.resize(1);
   events[0] = new MidiEventList;
   timemapvalid=0;
   timemap.clear();
   events.resize(0);                     // naughty line (orphaned content left on heap)
}
```

The last line "events.resize(0)" will hide access to the newly created empty event list pointed to by events[0].  Thus the code in joinTracks:

```
clear_no_deallocate();
delete events[0];
events.resize(0);
```

Is incorrectly trying to delete events[0] which is strictly undefined since the size of the events vector is 0 coming out of clear_no_deallocate().  This is the out-of-bound error that you report. On my computer configuration it seems that it might luckily resolve the memory leak created in clear_no_deallocate() by deleting from the old hidden contents of events, since I have not noticed the problem before.

Replacing "delete events[0]" with "events.clear()" is OK.  But if I fix the memory leak in clear_no_deallocate(), it will pop up here instead.  So really you are reporting the memory leak in clear_no_deallocate() which I have fixed. "events.resize(0)" that follows the "delete events[0]" line is virtually identical to "events.clear()".  It looks like vector::clear() is supposed to deallocate its contents, while vector::resize() does not.  So to be infinitesimally faster, .resize() should be used so that new space does not need to be allocated when adding a new track again. 

I commented out the events.resize(0) at the end of clear_no_deallocate(), this will match the behavior of MidiFile::clear() which leaves behind a single empty track after deleting old track contents.  This should then fix the out-of-bound problem (some basic testing of the new code looks good). The line "delete events[0]" will then need to be kept because there is one empty track that needs to be removed before putting the merged track into events.

============================================

For the splitTracks() problem you report:

```
// Jorden Thatcher Feb-5-2016
   // changed i<=length to i<length, was causing out of index range error
   for (i=0; i<length; i++) {
      if ((*events[0])[i].track > maxTrack) {
          maxTrack = (*events[0])[i].track;
      }
   }
```

Perhaps you have old code?  The current version of the code has i<length since at least a year ago:

https://github.com/craigsapp/midifile/blame/master/src-library/MidiFile.cpp#L838-L842

```
   for (i=0; i<length; i++) {
	      if ((*events[0])[i].track > maxTrack) {
	          maxTrack = (*events[0])[i].track;
	      }
   }
```

And the earliest version of the code posted on Github also has i<length:

https://github.com/craigsapp/midifile/blob/deb86ade2ea02a908975687ad733f7a859e25dc5/src-library/MidiFile.cpp#L1401-L1405

```
   for (i=0; i<length; i++) {
      if ((*events[0])[i].track > maxTrack) {
          maxTrack = (*events[0])[i].track;
      }
   }
```

Looking through the code, I don't see any other location which you might instead be referring to.

============================================

[The joinTracks() function moves a 2-dimensional array of MIDI messages into a single list (perhaps it would be better to keep the messages in both representations at the same time since switching between multi and single track modes is costly).  Doing this would avoid any problems related to this issue.]

**Comment by JThatcher2016** [comment]
> Perhaps you have old code? The current version of the code has i<length since at least a year ago:

No I wasn't aware of that, I just downloaded this code about 3 days ago. Anyway, hoped my accidental discovery of the memory leak helped.
