### ISSUE TITLE
MidiFile::doTimeAnalysis (buildTimeMap) seems to make error in '~MidiFile'

### ISSUE THREAD

**Issue by Bakers-Avenue** [craigsapp/midifile#15]
Hello,

The codes below are making error in destructor randomly in main() function.

    MidiFile midifile("test.mid");
    midifile.doTimeAnalysis();    
    return 0;

When I comment out the second line(doTimeAnalysis), there's no error.
Please refer to the attached project and screenshots for repro.

[MidiFileLibraryTest.zip](https://github.com/craigsapp/midifile/files/130106/MidiFileLibraryTest.zip)

[screenshots_from_call_stack.zip](https://github.com/craigsapp/midifile/files/130104/screenshots_from_call_stack.zip)

**Comment by craigsapp** [comment]
I got an error with your program and input data.  Tracking down the problem it seems to be caused by an off-by-one indexing of a vector.  Here is the fix: https://github.com/craigsapp/midifile/commit/72509d1fc275fcbfba8b1ba2ac3c0e4c76e03b76
When I apply that fix, your program with given test data now works for me.

**Comment by Bakers-Avenue** [comment]
I've checked the code with that fix and the error has gone.
Thanks for the quick resolution.
