### ISSUE TITLE
error compiling.

### ISSUE THREAD

**Issue by Duality4Y** [craigsapp/midifile#17]
I get errors running make library
this is the output:
http://pastebin.com/wHnu6P60

I saw no requirments for installing (like dependencies and other libraries it depends on)

**Comment by craigsapp** [comment]
Sorry, this is due to code that I added yesterday.  The main problem is that I needed to add
```cpp
#include <string>
```
to include/MidiMessage.h, since I added functions which take a string type argument (this did not cause a problem when I compiled it either due to a different compiler, or a file loaded before this one which already had the string header file included.

Also fixed are a few signed/unsigned comparisons reported as warnings in your compiler (tell me if I missed any).

Commit which should fix the problems: https://github.com/craigsapp/midifile/commit/ed85a64d74d3db86beb339d93498003dd9a06000

**Comment by Duality4Y** [comment]
thanks for the fast response!
I will try it out right away.

**Comment by Duality4Y** [comment]
it compiles! :)
