### ISSUE TITLE
Compiling in windows

### ISSUE THREAD

**Issue by serp0** [craigsapp/midifile#18]
Just a heads up. When compiling in Windows using the "visual-studio" fix, the process fails. MidiMessage.cpp is missing "#include <iterator>". It has to be added manually in order to generate the library file. 

p.s. - this library is awesome

EDIT: I'm getting undefined refrence errors with MidiFile inclusion

Code:
```
#include "MidiFile.h"
#include "Options.h"
#include <iostream>

using namespace std;

int main(int argc, char** argv)
{
    MidiFile outTrack; //Declares a midi obj named seed track

    //Controls
    int totalTracks = 60; //sets desired number of output tracks

    outTrack.read("orig.mid"); //Assigns file to outTrack obj. Contents of file is transfered to obj. File must be named "orig".

    int eventsTot = outTrack.getEventCount(0); //Gets the total number of events from original midi file

    for(int a = 1; a <= totalTracks ; a++){ //Main Track Loop. Loops through the desired number of tracks

        outTrack.addTrack();


        for(int i=0;i<=eventsTot;i++){ //Main Event Loop. Loops through each event of the orig track


        }

    }

    cout << "Hello world!" << endl;
    return 0;
}

```
Errors:

||=== Build: Debug in midiii (compiler: GNU GCC Compiler) ===|
obj\Debug\main.o||In function `main':|
C:\Users\Desktop\New folder\midiii\main.cpp|9|undefined reference to `MidiFile::MidiFile()'|
C:\Users\Desktop\New folder\midiii\main.cpp|14|undefined reference to `MidiFile::read(char const*)'|
C:\Users\Desktop\New folder\midiii\main.cpp|16|undefined reference to `MidiFile::getEventCount(int)'|
C:\Users\Desktop\New folder\midiii\main.cpp|20|undefined reference to `MidiFile::addTrack()'|
C:\Users\Desktop\New folder\midiii\main.cpp|31|undefined reference to `MidiFile::~MidiFile()'|
C:\Users\Desktop\New folder\midiii\main.cpp|31|undefined reference to `MidiFile::~MidiFile()'|
||error: ld returned 1 exit status|
||=== Build failed: 7 error(s), 0 warning(s) (0 minute(s), 0 second(s)) ===|

**Comment by craigsapp** [comment]
```
obj\Debug\main.o||In function main':| C:\Users\Desktop\New folder\midiii\main.cpp|9|undefined reference toMidiFile::MidiFile()'|
```
This means that the compiler cannot find the compiled code for the MidiFile class (but it knows about the include directory and .h files inside it).  You will have to tell the compiler where the midifile library is located in several possible ways: (1) create a static library for the midifile library (a file ending in .lib), and include it in your project for linking in this final step (2) create a dynamic library for the midifile library, or (3) just copy all of the .cpp and .h files for the midifile code within the same directory as your project files (and include them in the project).  The Options class can be deleted.

If you want to iterate over all MIDI events in the file, this is a good template:

```cpp
outTrack.read("orig.mid");
for (int track=0; track < outTrack.size(); track++) {
   for (int event=0; event < outTrack[track].size(); event++) {
      if (outTrack[track][event].isNoteOn()) {
         cout << "FOUND NOTE ON" << endl;
      }
   }
}
```

Note that `outTrack.getEventCount(0)` is equivalent to `outTrack[0].size()`.  It looks like you will be needing to move the `eventsTot` code inside of the first loop, and make the track parameter a variable rather than always 0; otherwise you will be looping over every track, and then looping only over the events in the first track (which may be what you want, of course).

If you want to do a one-dimensional iteration, you can convert the MIDI file into a Type-0 (single track) file:

```cpp
outTrack.read("orig.mid");
outTrack.joinTracks();
for (int event=0; event < outTrack[0].size(); event++) {
   if (outTrack[0][event].isNoteOn()) {
      cout << "FOUND NOTE ON" << endl;
   }
}
```

Note that the code
```cpp
 outTrack.addTrack();
```
in your sample program will add 60 extra tracks to the original "outTrack" contents read from orig.mid (so there will be more than 60 tracks after you go through your loop).  Also note that an empty MidiFile always contains one track, so adding 60 tracks will result in a final track count of 61 tracks.  You can also add 60 tracks to a MidiFile in one step with the MidiFile::addTracks(60); function call.

**Comment by serp0** [comment]
Thanks for the fast response. I think I botched the static library generation. Including the .cpp and headers in my project is working so I'll stick with that for now.

**Comment by craigsapp** [comment]
That is the easiest way.  I'll also think about making a version of the code where all the classes are merged into a single .cpp and .h file (midifile.h and midifile.cpp) to make that even easier.
