### ISSUE TITLE
[Suggestion] linking 'sustain on(127)' and 'sustain off(0)' midievents in a function

### ISSUE THREAD

**Issue by Bakers-Avenue** [craigsapp/midifile#20]
Hi Craig,

Currently we can get a note-off event of specific note-on event by using linkNotePairs() and getLinkedEvent(). They're very useful.
How about having similar utility function for linking a sustain-on(127) event and a sustain-off(0) event which is placed at the closest next position after the sustain-on event on the same channel, and vice versa.
In that case, some exceptional situations need to be considered. For example,

1. In a channel which doesn't use any sustain-on event except a initial sustain-off event, we can't get linked sustain-on event of  initial sustain-off event.
2. In a channel which ends without sustain-off event(if that's possible), we can't get linked sustain-off event of the last sustain-on event.

Sustain midi messages are very important articulation especially in keyboard instruments and they logically can be considered as on-and-off pairs if they're used properly.
Perhaps you could find more midi messages can be treated as pairs.

Thanks in advance.

Kind regards,

Peter

**Comment by craigsapp** [comment]
Hi Peter,

Yes, that would be a useful addition.  I'll implement it soon.

For case (1) where there is an initial sustain-off, which could happen if the MIDI file wants to guarantee that the sustain pedal is not stuck on), then that would not be a problem.  The sustain-off message would just not be linked to a sustain-on.

For case (2) a sustain-on without a sustain-off, that would work the same way in that it would not be linked.  It would be up to the user to decide what to do.  In this case the  duration of an unlinked sustain-on should be the time from the sustain-on to the end of the file (I'll write a convenience function for getting the total duration of the file if I haven done so yet).  Percussion-channel notes work in a similar way: typically percussion instruments only have a note-on and no note-off.  For Percussion, however, the duration would not be to the end of the file, but the duration of the sound (which is undefined in the file since it is determined by the synthesizer).

I'll probably implement this inside of linkNotePairs(), and I will create an alias function called linkEventPairs(), since this name makes more sense as it is not only linking note-on/offs.

The on-state for sustains are the values 64-127 and sustain-offs are the range 0-63.  So I will generalized the on/off states to those ranges rather than only 0 for off and 127 for on.

I will also implement on/off pairings for other General MIDI controllers:

```
hex dec  name                                    range
40  64   Hold pedal (Sustain) on/off             0..63=off  64..127=on
41  65   Portamento on/off                       0..63=off  64..127=on
42  66   Sustenuto Pedal on/off                  0..63=off  64..127=on
43  67   Soft Pedal on/off                       0..63=off  64..127=on
44  68   Legato Pedal on/off                     0..63=off  64..127=on
45  69   Hold Pedal 2 on/off                     0..63=off  64..127=on
50  80   General Purpose Button                  0..63=off  64..127=on
51  81   General Purpose Button                  0..63=off  64..127=on
52  82   General Purpose Button                  0..63=off  64..127=on
53  83   General Purpose Button                  0..63=off  64..127=on
54  84   Undefined on/off                        0..63=off  64..127=on
55  85   Undefined on/off                        0..63=off  64..127=on
56  86   Undefined on/off                        0..63=off  64..127=on
57  87   Undefined on/off                        0..63=off  64..127=on
58  88   Undefined on/off                        0..63=off  64..127=on
59  89   Undefined on/off                        0..63=off  64..127=on
5A  90   Undefined on/off                        0..63=off  64..127=on
7A 122   Local Keyboard On/Off                   0..63=off  64..127=on
```

**Comment by Bakers-Avenue** [comment]
Glad to hear that. I was thinking that name, linkEventPairs().
It'll be better if we can handle repeated 'on' or 'off' by just ignoring or cleaning that 'meaningless' events.

**Comment by craigsapp** [comment]
So you mean that if a MIDI file has an event message paring (such as for sustain) of:
```
    on1  on2  off3  off4  off5  on6  on7  on8  off9
```
then any repeated similar state should be ignored (remain unlinked):
```
    on1 -> off3
    on2 -> unlinked
    off3 -> on1
    off4 -> unlinked
    off5 -> unlinked
    on6 -> off9
    on7 -> unlinked
    on8-> unlinked
    off9 -> on6
```

This will map to how a MIDI synthesizer handles the sustain pedal.  In other words, if a sustain message repeats the previously stated on/off state, then it won't really matter since that state is already in effect.  So any sustain message which repeats the same previously active state will be ignored and have no linkages according to how I am thinking about it.

**Comment by craigsapp** [comment]
Hi Peter,

I just posted a new version of the midifile library which should now link sustain on/off messages:  https://github.com/craigsapp/midifile/commit/ae9600fa252095c0a7522c3e5030ae86aad26625

Here is a basic test program which seems to show that the new code works properly:

```cpp
#include "MidiFile.h"
#include <iostream>
#include <iomanip>

using namespace std;

void printEventLinkInfo(MidiFile& midifile);

int main(void) {
   MidiFile outfile;

   int track   = 0;
   int tick    = 0;
   int channel = 0;
   int sustain = 64;
   int on      = 127;
   int off     = 0;

   outfile.addController(track, tick, channel, sustain, on);
   outfile.addNoteOn(track, tick, channel, 60, 64);
   tick += 120;
   outfile.addNoteOff(track, tick, channel, 60);
   outfile.addNoteOn(track, tick, channel, 67, 64);
   // add redundant sustain-on message:
   outfile.addController(track, tick, channel, sustain, on);
   tick += 120;
   outfile.addNoteOff(track, tick, channel, 67);
   outfile.addController(track, tick, channel, sustain, off);
   tick += 120;
   // add redundant sustain-off message:
   outfile.addController(track, tick, channel, sustain, off);
   tick += 120;
   // add redundant sustain-off message:
   outfile.addController(track, tick, channel, sustain, off);
   tick += 120;
   // add unpairable sustain-on message:
   outfile.addController(track, tick, channel, sustain, on);

   outfile.linkEventPairs();
   printEventLinkInfo(outfile);

   return 0;
}


void printEventLinkInfo(MidiFile& midifile) {
   int i, j;
   MidiEvent* link;
   for (i=0; i<midifile[0].size(); i++) {
      cout << i;
      link = midifile[0][i].getLinkedEvent();
      if (link) {
         for (j=0; j<midifile[0].size(); j++) {
            if (&midifile[0][j] == link) {
               cout << " --> " << j;
            }
         }
      }
      cout << "\t0x" << hex << (int)midifile[0][i][0];
      for (j=1; j<midifile[0][i].size(); j++) {
         cout << " " << dec << (int)midifile[0][i][j];
      }
      cout << endl;
   }
}
```

Output from this program:

```
0 --> 6	0xb0 64 127
1 --> 2	0x90 60 64
2 --> 1	0x90 60 0
3 --> 5	0x90 67 64
4	0xb0 64 127
5 --> 3	0x90 67 0
6 --> 0	0xb0 64 0
7	0xb0 64 0
8	0xb0 64 0
9	0xb0 64 127
```

The first number on a line is the index number of a message.  If there is a link to another message in the file, there is an arrow to the index for that event.  Then there is a hex byte printed for the MIDI command and the message's parameters in decimal format after that.

Event 0 is a sustain-on which links to event 6 which is the first sustain-off to occur after the sustain-on.

Event 4 is a redundant sustain-on message which is ignored.

Events 7 and 8 are redundant sustain-off messages which are ignored.

Event 9 is a sustain-on message with no paired sustain-off message.

Other General MIDI on/off controller messages should also be linked by MidiFile::linkEventPairs(), as listed previously in this thread.  The function MidiFile::linkNotePairs() is an alias for MidiFile::linkEventPairs(), and controllers and notes will be linked if you call either of these functions.

Although I have not checked (because the code is obviously correct :-), controller messages in each MIDI channel should be linked independently from controller messages on other channels.

A caveat is that linking only occurs within a single track (this was also true previously for note on/off linking).   If you have a sustain-on in channel 12 in one track, and a sustain-off in channel 12 in another track, they will not link to each other.   If cross-track linking is needed, then MidiFile::joinTracks() should be called before MidiFile::linkEventPairs(), and MidiFile::splitTracks() can then be called to restore the multi-track state for the file (but the link analysis *should* still remain valid).

**Comment by Bakers-Avenue** [comment]
Hi Craig,

Thanks for your super-fast extension. I was waiting for this :).
Maybe I'll be the first person who uses this function practically.
I'm currently using midi files which have hundreds of segments in terms of track and channels for passing some semantics to main code, so I should try this feature with jointTrack() and splitTracks().
I guess it won't be any problem if joinTracks() and splitTracks() are reversible to each other for now.

Best regards,
Peter

**Comment by craigsapp** [comment]
Yes, joinTracks and splitTracks should be completely reversible (if not then there is a bug).  The links are stored as pointers to the paired MidiMessage, and the addresses of these Messages will remain the same when a MidiFile is in either a single or multi-track state.
