### ISSUE TITLE
variable length values must not be >4 bytes

### ISSUE THREAD

**Issue by derselbst** [craigsapp/midifile#27]
Why are you writing up to 5 bytes in [MidiFile::writeVLValue](https://github.com/craigsapp/midifile/blob/462f55a906faa874a9b94fee18d4efd6945da7f8/src-library/MidiFile.cpp#L2646)? I don't think this is correct according to [Midi 1.1 spec](http://www.music.mcgill.ca/~ich/classes/mumt306/midiformat.pdf):

`The largest number which is allowed is 0FFFFFFF so that the variable-length representations must fit in 32 bits in a routine to write variable-length numbers.`

I.e. that `aValue == 0x0FFFFFFF` gives `VLValue of 0x7FFFFFFF`. Fluidsynth's midi parser actually complains when reading midi files written with this library.

**Comment by craigsapp** [comment]
You are right.  Here is what I see from the MIDI 1.0 specification on the MIDI Manufacturers Association website version of the specs (chapter 4 about standard MIDI files):

https://www.midi.org/articles/the-midi-association-offers-free-download-of-the-midi-1-0-specifications-document

> The largest number which is allowed is `0FFFFFFF` so that the variable-length representation must fit in 32 bits in a routine to write variable-length numbers.  Theoretically, larger numbers are possible, but 2 x 10^8 96ths of a beat at a fast tempo of 500 beats per minute is four days, long enough for any delta-time!

I was probably programming from memory of the spec thinking that it allowed up to `0xFFFFFFFF`, or perhaps I was misreading `0FFFFFFF` as a typo of `0xFFFFFFFF`.

The variable length value for `0FFFFFFF` is `FF FF FF 7F`, or in little-endian compact form `7FFFFFFF` as you mention.

Here is the updated version of the code: Commit 695eb09

----------------------

There is a small utility program in the example src-programs directory/folder:
     https://github.com/craigsapp/midifile/blob/master/src-programs/vlv.cpp#L169-L216

This one had the correct VLV generating algorithm:

```bash
make vlv
$ bin/vlv 0x0FFFFFFF
ff ff ff 7f

$ bin/vlv 0x10000000
Error: number too large to handle
```
-----------------

Here is a sample program to demonstrate the new behavior of large VLV values:

```cpp
#include "MidiFile.h"
#include <iostream>

int main(void) {
   int track     = 0;
   int starttime = 0;
   int stoptime  = 0x0FFFFFFF;
   int channel   = 0;
   int pitch     = 60;
   int velocity  = 127;

   MidiFile midifile;
   midifile.addNoteOn(track, starttime, channel, pitch, velocity);
   midifile.addNoteOff(track, stoptime, channel, pitch);
   midifile.writeHex(std::cout);

   return 0;
}
```

Here is the output of the program:

```
4d 54 68 64 00 00 00 06 00 00 00 01 00 78 4d 54 72 6b 00 00 00 0f 00 90 3c
7f ff ff ff 7f 90 3c 00 00 ff 2f 00
```
parsing by hand:

```
4d 54 68 64     == "MTrk": start of standard MIDI file header chunk.
00 00 00 06     == 6: Number of bytes to file in header.
00 00           == Type-0 standard MIDI file.
00 01           == One track chunck to follow.
00 78           == Ticks per quarter note.
                == End of header chunk
4d 54 72 6b     == "MThd": strat of track chunk. 
00 00 00 0f     == 16 bytes left in track chunk.
00              == VLV delta time of first message.
   90 3c 7f   == first message (note-on, middle-C, maximum velocity)
ff ff ff 7f     == VLV delta time of next message.
   90 3c 00   == note-off on middle-C.
00              == VLV delta time of last message.
     ff 2f 00   == end-of-track meta message.
```

Now adjusting the timings so that the delta time will be too large:

```cpp
#include "MidiFile.h"
#include <iostream>

int main(void) {
   int track     = 0;
   int starttime = 0;
   int stoptime  = 0x10000000;
   int channel   = 0;
   int pitch     = 60;
   int velocity  = 127;

   MidiFile midifile;
   midifile.addNoteOn(track, starttime, channel, pitch, velocity);
   midifile.addNoteOff(track, stoptime, channel, pitch);
   midifile.writeHex(std::cout);

   return 0;
}
```

Now the output of the program is:

```
Error: number too large to convert to VLV
4d 54 68 64 00 00 00 06 00 00 00 01 00 78 4d 54 72 6b 00 00 00 0f 00 90 3c
7f ff ff ff 7f 90 3c 00 00 ff 2f 00
```

In this case the contents that is output is the same (other than the error message to standard error), with the delta time clipped to the maximum allowed in standard MIDI files.


-----------------

> Fluidsynth's midi parser actually complains when reading midi files written with this library.

This should be a separate problem, unless you are trying to store a delta time larger than `0x0FFFFFFF`.  If you input valid delta times up to `0x0FFFFFFF`, then the variable-length values should only be up to 4 bytes long.  If you provide a time larger than `0x0FFFFFFF`, then this library was previously incorrectly generating a 5-byte VLV, adding an extra bytes for the overflow.  I adjusted the library to clip any overflow to the maximum value in case this is the problem (but note the MIDI file timings will also be incorrect due to the automatically adjusted delta-times sizes).

If you are not using an overflow delta time, there is some other problem happening.  If you post a sample MIDI file or a description of how you made the MIDI file, I can test with fluidsynth to see what the problem could be.

----------------------

Here is what I think the problem is:  while generating the above sample test program, I notice that the default state of a MidiFile object is TIME_STATE_ABSOLUTE:
https://github.com/craigsapp/midifile/blob/a3cb4e4f4ba5ef6981d8ff02b5b163fde49b0ce3/src-library/MidiFile.cpp#L54
This means that the time values in the object are not delta-times, but rather absolute tick times.  When you write a MIDI File, the writing function automatically converts the absolute time values into delta time values:
https://github.com/craigsapp/midifile/blob/a3cb4e4f4ba5ef6981d8ff02b5b163fde49b0ce3/src-library/MidiFile.cpp#L554-L557
If you have a smaller absolute time following a larger absolute time, the delta time will be negative, and this was probably forcing an incorrect 5-byte VLV to be generated by the library.
https://github.com/craigsapp/midifile/blob/a3cb4e4f4ba5ef6981d8ff02b5b163fde49b0ce3/src-library/MidiFile.cpp#L1174-L1178
If you are using delta times rather than absolute times, then this is almost certainly the problem.

If you want to work only in delta times, then change the time format after creating the MidiFile object and before writing any events to it:

```cpp
MidiFile midifile;
midifile.deltaTicks();
// write some events
midifile.write("test.mid");
```

Here is an example program which demonstrates the problem that I think you are having:

```cpp
#include "MidiFile.h"
#include <iostream>
int main(void) {
   int track     = 0;
   int delta1    = 1000;
   int delta2    = 50;
   int channel   = 0;
   int pitch     = 60;
   int velocity  = 127;
   MidiFile midifile;
   midifile.addNoteOn(track, delta1, channel, pitch, velocity);
   midifile.addNoteOff(track, delta2, channel, pitch);
   midifile.writeHex(std::cout);
   return 0;
}
```

The problem in this program is that `delta1` and `delta2` are being treated as absolute times rather than delta times, since absolute time is the initial behavior of a MidiFile object. The note-on is set to absolute time 1000, and the note-off is set to absolute time 50, so the delta time between them is -950. (The MidiFile::writeHex(), or any MidiFile::write() function will temporarily convert the timings into delta times while writing the file which is where the -950 is coming from).

Above program's output (first line to standard error, rest to standard output):

```
Error: number too large to convert to VLV
4d 54 68 64 00 00 00 06 00 00 00 01 00 78 4d 54 72 6b 00 00 00 10 87 68 90
3c 7f ff ff ff 7f 90 3c 00 00 ff 2f 00
```

The delta time between the note-on/note-off pair is "ff ff ff 7f" which is the limited version of -950 (`0xFFFFFC4A`).

Instead the above program should have set the MidiFile object to deltaTicks() mode:

```cpp
#include "MidiFile.h"
#include <iostream>
int main(void) {
   int track     = 0;
   int delta1    = 1000;
   int delta2    = 50;
   int channel   = 0;
   int pitch     = 60;
   int velocity  = 127;
   MidiFile midifile;
   midifile.deltaTicks();
   midifile.addNoteOn(track, delta1, channel, pitch, velocity);
   midifile.addNoteOff(track, delta2, channel, pitch);
   midifile.writeHex(std::cout);
   return 0;
}
```

or the times should have ben specifed as absolute ticks rather than delta ticks:

```cpp
#include "MidiFile.h"
#include <iostream>
int main(void) {
   int track     = 0;
   int abstime1    = 1000;
   int abstime2    = 1050;
   int channel   = 0;
   int pitch     = 60;
   int velocity  = 127;
   MidiFile midifile;
   midifile.addNoteOn(track, delta1, channel, pitch, velocity);
   midifile.addNoteOff(track, delta2, channel, pitch);
   midifile.writeHex(std::cout);
   return 0;
}
```

Both of these programs should output:

```
4d 54 68 64 00 00 00 06 00 00 00 01 00 78 4d 54 72 6b 00 00 00 0d 87 68 90
3c 7f 32 90 3c 00 00 ff 2f 00
```

Where "32" (decimal 50) is the delta time between the note-on and note-off.

==============================

If you already knew that the default format for time values was absolute rather than delta ticks, then another problem is that absolute ticks must be time sorted before writing the file or converting into delta ticks.  This is not done automatically for efficiency reasons (if you know all times are time sorted, then you don't want to sort them into time order).

Here is an example program which demonstrates the problem where the note-off is stored in the MIDI file before the note-on:

```cpp
#include "MidiFile.h"
#include <iostream>
int main(void) {
   int track     = 0;
   int delta1    = 1000;
   int delta2    = 1050;
   int channel   = 0;
   int pitch     = 60;
   int velocity  = 127;
   MidiFile midifile;
   midifile.addNoteOff(track, delta2, channel, pitch);
   midifile.addNoteOn(track, delta1, channel, pitch, velocity);
   midifile.writeHex(std::cout);
   return 0;
}
```

This outputs:

```
Error: number too large to convert to VLV
4d 54 68 64 00 00 00 06 00 00 00 01 00 78 4d 54 72 6b 00 00 00 10 88 1a 90
3c 00 ff ff ff 7f 90 3c 7f 00 ff 2f 00
```
To fix this problem, run MidiFile::sortTracks() before writing the MIDI file:

```cpp
#include "MidiFile.h"
#include <iostream>
int main(void) {
   int track     = 0;
   int delta1    = 1000;
   int delta2    = 1050;
   int channel   = 0;
   int pitch     = 60;
   int velocity  = 127;
   MidiFile midifile;
   midifile.addNoteOff(track, delta2, channel, pitch);
   midifile.addNoteOn(track, delta1, channel, pitch, velocity);
   midifile.sortTracks();
   midifile.writeHex(std::cout);
   return 0;
}
```

Corrected output:

```
4d 54 68 64 00 00 00 06 00 00 00 01 00 78 4d 54 72 6b 00 00 00 0d 87 68 90
3c 7f 32 90 3c 00 00 ff 2f 00
```



If you know your absolute times are not time-sorted, or you don't know if they are, then you should call MidiFile::sortTracks() before writing a MIDI file:

```cpp
MidiFile midifile;
// write some absolute tick messages in any order
midifile.sortTracks();
midifile.write("test.mid");
```

Another caveat which I have fixed is that you should not sort delta times (this could have also been your problem).  But I have just fixed the sorting function so that it ignores a sort request if the time state of the MIDI file is delta ticks:

https://github.com/craigsapp/midifile/blob/a3cb4e4f4ba5ef6981d8ff02b5b163fde49b0ce3/src-library/MidiFile.cpp#L1993-L2000
```cpp
   qsort(trackData.data(), trackData.size(), sizeof(MidiEvent*), eventcompare);
```
changed to:

https://github.com/craigsapp/midifile/blob/695eb0908bde64819642adda02e5fa2e2ea5337a/src-library/MidiFile.cpp#L2004-L2007

```cpp
   if (oldTimeState == TIME_STATE_ABSOLUTE) {      
      qsort(trackData.data(), trackData.size(), sizeof(MidiEvent*), eventcompare);   
    }
```

If you convert a MidiFile object immediately to delta ticks, then you do not need to sort, but the new version of the library will automatically suppress a sort request if the object is in the delta tick state.

Another problem which I just fixed is that the `const string& filename` and `istream& input` constructors were set to delta times by default.  But this is silly, and I switched all constructors to start the MidiFile object in the absolute time state (hopefully this will not mess anyone up, as I seem to have never used those constructors myself).

**Comment by derselbst** [comment]
> If you have a smaller absolute time following a larger absolute time, the delta time will be negative, and this was probably forcing an incorrect 5-byte VLV to be generated by the library.

That's what I was doing. In addition I forgot MidiFile::sortTracks() :/

Thanks!

**Comment by craigsapp** [comment]
I added an error message to make tracking down the negative delta tick problem much easier.  See commit b40bee0

Example program to produce the error (note-off is stored before note-on):

```cpp
#include "MidiFile.h"
#include <iostream>
int main(void) {
   int track     = 0;
   int time1     = 1000;
   int time2     = 1050;
   int channel   = 0;
   int pitch     = 60;
   int velocity  = 127;
   MidiFile midifile;
   midifile.addNoteOff(track, time2, channel, pitch);
   midifile.addNoteOn(track, time1, channel, pitch, velocity);
   midifile.writeHex(std::cout);
   return 0;
}
```

Output from the program with the error:

```
Error: negative delta tick value: -50
Timestamps must be sorted first (use MidiFile::sortTracks() before writing).
Error: number too large to convert to VLV
4d 54 68 64 00 00 00 06 00 00 00 01 00 78 4d 54 72 6b 00 00 00 10 88 1a 90
3c 00 ff ff ff 7f 90 3c 7f 00 ff 2f 00
```

Fixed version of the program:

```cpp
#include "MidiFile.h"
#include <iostream>
int main(void) {
   int track     = 0;
   int time1     = 1000;
   int time2     = 1050;
   int channel   = 0;
   int pitch     = 60;
   int velocity  = 127;
   MidiFile midifile;
   midifile.addNoteOff(track, time2, channel, pitch);
   midifile.addNoteOn(track, time1, channel, pitch, velocity);
   midifile.sortTracks();
   midifile.writeHex(std::cout);
   return 0;
}
```

New output with no error messages:

```
4d 54 68 64 00 00 00 06 00 00 00 01 00 78 4d 54 72 6b 00 00 00 0d 87 68 90
3c 7f 32 90 3c 00 00 ff 2f 00
```

**Comment by derselbst** [comment]
works fine, thanks!
