### ISSUE TITLE
while(1)

### ISSUE THREAD

**Issue by huimiao638** [craigsapp/midifile#28]
when i want to read file   context {0x00 0x00 .....}
MidiFile::read 
int Binasc::writeToBinary
 will while(1)

**Comment by huimiao638** [comment]
int c = file.peek();
if (c == EOF) {
  if (file.eof())
    // end of file
  else
    // error
} else {
  // do something with 'c'
}

> http://stackoverflow.com/questions/6283632/how-to-know-if-the-next-character-is-eof-in-c

**Comment by craigsapp** [comment]
我不明白。

This midifile library is used to avoid reading/writing raw binary data to a file.  If you want to read MIDI file data directly from a file, then you can look are the core of the reading process for the library:

https://github.com/craigsapp/midifile/blob/695eb0908bde64819642adda02e5fa2e2ea5337a/src-library/MidiFile.cpp#L239-L524

And the writing process:

https://github.com/craigsapp/midifile/blob/695eb0908bde64819642adda02e5fa2e2ea5337a/src-library/MidiFile.cpp#L534-L654

------------------------

Or if you have a general question about reading bytes from a file (in C++), then your main problem is do not use `ifstream::peek()`, since it is not necessary in the case you are trying to apply it, and the way you are trying to use it will cause an infinite loop.  Use `ifstream::get()` instead.

`file.peek()` is used to look at the next character in a file without removing it from the read buffer.  If at the end of the file, then EOF is returned.  This is an infinite loop, since nothing is being removed from the file read buffer:

```cpp
int value = file.peek()
while (value != EOF) {
    value = file.peek();
}
```
Each time `file.peek()` is called, the same byte is returned.  If 'a' was returned, it will always be returned, and EOF will never be found.  In the following example, each time `file.get()` is called, a new byte will be read.  So this is not an infinite loop:

```cpp
int value = file.get()
while (value != EOF) {
    value = file.get();
}
```

http://www.cplusplus.com/reference/istream/istream/get

http://www.cplusplus.com/reference/istream/istream/peek

Here is a complete example

```cpp
#include <iostream>
#include <iomanip>
#include <fstream>
#include <stdlib.h>

using namespace std;

int main(int argc, char** argv) {
   if (argc != 2) {
      exit(1);
   }
   ifstream input;
   input.open(argv[1], ios::binary);
   if (!input.is_open()) {
      cerr << "Could not open file " << argv[1] << " for reading" << endl;
      exit(1);
   }
   int linebreak = 25;
   int counter = 0;
   int character;
   while ((character = input.get()) != EOF) {
      cout << (character < 0x10 ? "0" : "") << hex << character;
      cout << (++counter % 25 ? " " : "\n");
   }
   if (counter % 25) {
      cout << "\n";
   }
   return 0;
}
```

Here is sample output, using the above program file as the contents to read:

```
23 69 6e 63 6c 75 64 65 20 3c 69 6f 73 74 72 65 61 6d 3e 0a 23 69 6e 63 6c
75 64 65 20 3c 69 6f 6d 61 6e 69 70 3e 0a 23 69 6e 63 6c 75 64 65 20 3c 66
73 74 72 65 61 6d 3e 0a 23 69 6e 63 6c 75 64 65 20 3c 73 74 64 6c 69 62 2e
68 3e 0a 0a 75 73 69 6e 67 20 6e 61 6d 65 73 70 61 63 65 20 73 74 64 3b 0a
0a 69 6e 74 20 6d 61 69 6e 28 69 6e 74 20 61 72 67 63 2c 20 63 68 61 72 2a
2a 20 61 72 67 76 29 20 7b 0a 20 20 20 69 66 20 28 61 72 67 63 20 21 3d 20
32 29 20 7b 0a 20 20 20 20 20 20 65 78 69 74 28 31 29 3b 0a 20 20 20 7d 0a
20 20 20 69 66 73 74 72 65 61 6d 20 69 6e 70 75 74 3b 0a 20 20 20 69 6e 70
75 74 2e 6f 70 65 6e 28 61 72 67 76 5b 31 5d 2c 20 69 6f 73 3a 3a 62 69 6e
61 72 79 29 3b 0a 20 20 20 69 66 20 28 21 69 6e 70 75 74 2e 69 73 5f 6f 70
65 6e 28 29 29 20 7b 0a 20 20 20 20 20 20 63 65 72 72 20 3c 3c 20 22 43 6f
75 6c 64 20 6e 6f 74 20 6f 70 65 6e 20 66 69 6c 65 20 22 20 3c 3c 20 61 72
67 76 5b 31 5d 20 3c 3c 20 22 20 66 6f 72 20 72 65 61 64 69 6e 67 22 20 3c
3c 20 65 6e 64 6c 3b 0a 20 20 20 20 20 20 65 78 69 74 28 31 29 3b 0a 20 20
20 7d 0a 20 20 20 69 6e 74 20 6c 69 6e 65 62 72 65 61 6b 20 3d 20 32 35 3b
0a 20 20 20 69 6e 74 20 63 6f 75 6e 74 65 72 20 3d 20 30 3b 0a 20 20 20 69
6e 74 20 63 68 61 72 61 63 74 65 72 3b 0a 20 20 20 77 68 69 6c 65 20 28 28
63 68 61 72 61 63 74 65 72 20 3d 20 69 6e 70 75 74 2e 67 65 74 28 29 29 20
21 3d 20 45 4f 46 29 20 7b 0a 20 20 20 20 20 20 63 6f 75 74 20 3c 3c 20 28
63 68 61 72 61 63 74 65 72 20 3c 20 30 78 31 30 20 3f 20 22 30 22 20 3a 20
22 22 29 20 3c 3c 20 68 65 78 20 3c 3c 20 63 68 61 72 61 63 74 65 72 3b 0a
20 20 20 20 20 20 63 6f 75 74 20 3c 3c 20 28 2b 2b 63 6f 75 6e 74 65 72 20
25 20 32 35 20 3f 20 22 20 22 20 3a 20 22 5c 6e 22 29 3b 0a 20 20 20 7d 0a
20 20 20 69 66 20 28 63 6f 75 6e 74 65 72 20 25 20 32 35 29 20 7b 0a 20 20
20 20 20 20 63 6f 75 74 20 3c 3c 20 22 5c 6e 22 3b 0a 20 20 20 7d 0a 20 20
20 72 65 74 75 72 6e 20 30 3b 0a 7d 0a 
```

**Comment by huimiao638** [comment]
if have  test.mid error contents :
` 00 00 00 00 00 00 00 00 00 00 00 00 ....`

MidiFile midifile;
int success = midifile.read(file_name);//will no return ;


`int Binasc::writeToBinary(ostream& out, istream& input) {
   char inputLine[1024] = {0};    // current line being processed
   int  lineNum = 0;              // current line number

   input.getline(inputLine, 1024, '\n');
   lineNum++;
   while (!input.eof()) { // **while(1)**
      processLine(out, inputLine, lineNum);
      input.getline(inputLine, 1024, '\n');
      lineNum++;
   }
   return 1;
}`

**Comment by craigsapp** [comment]
> if have test.mid error contents :
```
00 00 00 00 00 00 00 00 00 00 00 00 ....
```

This is not MIDI data, so I am still confused.  Here is a sample program to read the contents of a MIDI file:

```cpp
#include "MidiFile.h"
#include <iostream>
int main(void) {
   MidiFile midifile;
   int status = midifile.read("test.bin");
   std::cout << "MIDI file read was " 
             << (status ? "successful" : "unsuccessful") << std::endl;
   return !status;
}
```

Running the above program on [this binary data file](https://github.com/craigsapp/midifile/files/547095/test.txt) containing only "00" bytes (rename it `test.bin`), this is the result:

```
Bad MIDI data input
MIDI file read was unsuccessful
```

--------------------------------

Do you want to use the Binasc class independent of the rest of the midifile library?  That is possible; however, `Binasc` is more intended has a helper class in the midifile library, and generally you should not be using it directly.

Firstly, the Binasc class is built into the MidiFile::read function.  For example, suppose you have text file called `test2.txt` with this contents:

```
4d 54 68 64 00 00 00 06 00 00 00 01 00 78 4d 54 72 6b 00 00 00 0d 87 68 90
3c 7f 32 90 3c 00 00 ff 2f 00
```

Then you can read it into the MidiFile structure like this:

```
#include "MidiFile.h"
#include <iostream>
int main(void) {
   MidiFile midifile;
   int status = midifile.read("test2.txt");
   std::cout << "MIDI file read was " 
             << (status ? "successful" : "unsuccessful") << std::endl;
   return !status;
}
```

The output of the program given the contents above for `test2.txt`:

```
MIDI file read was successful
```

Here is same data parsed into a MidiFile structure and then printed as a higher-level binasc script:

```cpp
#include "MidiFile.h"
#include <iostream>

int main(void) {
   MidiFile midifile;
   int status = midifile.read("test2.txt");
   if (status) {
      std::cout << midifile;
   }
   return !status;
}
```

The output of this program using the above test data:

```
"MThd"			; MIDI header chunk marker
4'6			; bytes to follow in header chunk
2'0			; file format: Type-0 (single track)
2'1			; number of tracks
2'120			; ticks per quarter note

;;; TRACK 0 ----------------------------------
"MTrk"			; MIDI track chunk marker
4'13			; bytes to follow in track chunk
v1000	90 '60 '127	; note-on C4
v50	90 '60 '0	; note-off C4
v0	ff 2f v0	; end-of-track
```

This script can also be loaded into a MidiFile object as a text file.

-------------------------

If you want to output hex codes as a binary file (not necessarily a binary standard MIDI file), then here is an example.  Using the Binasc::writeToBinary(ostream& output, istream& input) is a bit specialized.  This version of the writing assumes that you have the input and output files already opened.

```cpp
#include "Binasc.h"
#include <iostream>
int main(void) {
   Binasc binasc;
   binasc.writeToBinary(std::cout, std::cin);
   return 0;
}
```

If you pipe this hex byte data into the compiled program:

```
48 65 6c 6c 6f 20 77 6f 72 6c 64 21 0a
```

It will output the compiled bytes (which represent ASCII characters):

```
Hello world!
```

example usage of the program on a command line:

```
    echo "48 65 6c 6c 6f 20 77 6f 72 6c 64 21 0a" | ./program
```

Note that the input into `Binasc::writeToBinary(ostream& output, istream& input)` is required to be text data.  You cannot have any binary data in `input`, and also perhaps cannot handle 00 bytes since the data is being stored in a C string, and '\0' is a string terminator (so input should be limited to UTF-7, i.e., low-bit ASCII).

The Binasc class is used to convert hex byte codes into bytes, and the reverse.  It is not used to write bytes to bytes as you seem to be wanting.

If you want to write a binary MIDI file, then here is an example:

```cpp
#include "MidiFile.h"
#include <iostream>
int main(void) {
   int track     = 0;
   int delta1    = 1000;
   int delta2    = 1050;
   int channel   = 0;
   int pitch     = 60;
   int velocity  = 127;
   MidiFile midifile;
   midifile.addNoteOff(track, delta2, channel, pitch);
   midifile.addNoteOn(track, delta1, channel, pitch, velocity);
   midifile.write("output.mid");
   return 0;
}
```

If you want to write a well-formed MIDI file which is encoded as hex bytes, then you would first read it into a MidiFile structure, and write as above:

```cpp
#include "MidiFile.h"
#include <iostream>
int main(void) {
   MidiFile midifile;
   midifile.read(std::cin);
   midifile.write("output.mid");
   return 0;
}
```

example usage in a terminal (could also open/read a text file with hex bytes):

```
echo "4d 54 68 64 00 00 00 06 00 00 00 01 00 78 4d 54 72 6b 00 00 00 0d 87 68 90 3c 7f 32 90 3c 00 00 ff 2f 00" | ./program
```

**Comment by craigsapp** [comment]
And here is another test:

given this text in `test2.txt`:

```
00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00
```

The following program:

```cpp
#include "MidiFile.h"
#include <iostream>

int main(void) {
   MidiFile midifile;
   int status = midifile.read("test2.txt");
   if (status) {
      std::cout << midifile;
   } else {
      std::cerr << "Error reading MIDI file" << std::endl;
   }
   return !status;
}
```

Replies with this message when running:

```
Bad MIDI data input
Error reading MIDI file
```

So when inputting either hex bytes as given in this example, or binary 00 bytes given in the previous message, I am not getting a stuck process when running with the example programs.

What operating system and compiler are you using?  Perhaps your problem is related to your setup being different from the one I am testing on (I was doing this with Apple's GCC compiler).

**Comment by huimiao638** [comment]
i use vs2013 vs2015 win10 x64

**Comment by tuxxon** [comment]
Is there a way(or code example) to extract a lyrics from a midi file?

**Comment by craigsapp** [comment]
> Is there a way(or code example) to extract a lyrics from a midi file?

I just added an example lyrics extraction program for you:

https://github.com/craigsapp/midifile/blob/master/src-programs/extractlyrics.cpp

Test input (the program can handle this ASCII representation of a MIDI file):

```
"MThd"
4'6
2'0
2'1
2'100

"MTrk"
4'126

v0 FF 51 03 t85  ; tempo: 85 quarter note per minute

v0 FF 05 05 "Some-"
v0   90 '65 '100
v200 90 '65 '0

v0 FF 05 06 "-where"
v0   90 '77 '100
v200 90 '77 '0

v0 FF 05 02 "o-"
v0   90 '76 '100
v100 90 '76 '0

v0 FF 05 04 "-ver"
v0   90 '72 '100
v50  90 '72 '0

v0 FF 05 03 "the"
v0   90 '74 '100
v50  90 '74 '0

v0 FF 05 05 "rain-"
v0   90 '76 '100
v100 90 '76 '0

v0 FF 05 04 "-bow"
v0   90 '77 '100
v100 90 '77 '0

v0   FF 2F 00
```

Resulting output with the command:

```bash
$ bin/extractlyrics -s input.txt
```

```
0	Some-
1.41176	-where
2.82353	o-
3.52941	-ver
3.88235	the
4.23529	rain-
4.94117	-bow
```

The `-s` option lists the starting time of the lyric text in the MIDI file.
