### ISSUE TITLE
getSpelling missing case? 

### ISSUE THREAD

**Issue by Linwood-F** [craigsapp/midifile#33]
When I first tried using this, I got a dump and tracked it back to this: 

In MidiMessage.cpp at approximately line 1089, the case 4 for base12pc, there is no case 0 contained in it.  Each other has a case 1, 0/2, 3.  This one omits the 0.  In music output from Musescore with more or less default settings, I had a note 76 at velocity 80, which causes on exit accidental to be set to 123456.

I think all that is needed is to add case 0, e.g. 

        case 2: base7pc = 2; accidental =  0; break;  // E

becomes

        case 0:   case 2: base7pc = 2; accidental =  0; break;  // E
 
I did not dig deeply to see if there is some underlying reason that case 4 should never have a velocity low order bits of 0, but Musescore certainly output it, so I believe it is more likely just an omission in this code.

I'm going to give a shot at submitting a PR but am rather a beginner at git, so apologies if I cannot get that to happen properly.

**Comment by Linwood-F** [comment]
I should comment that I did more looking into this, and I could not find any midi files that used this encoding technique of putting the low order 2 bits with spelling info, so I stopped using this routine at all. I think the PR I put in was correct, but I really think this whole routine is probably not something that gets used (which may be why no one stumbled on the missing case).

**Comment by craigsapp** [comment]
> but I really think this whole routine is probably not something that gets used (which may be why no one stumbled on the missing case).

I think so too.  I must not have used it myself enough to catch this error, but sometimes I have used this functionality to create MIDI files with preserved spelling of accidentals for people who want that data for a MIDI-analyzing software.  Not likely to find such files out in the wild as people who use MIDI don't seem to care about accidental spellings (even strangely if they want to generate graphical notation from the MIDI data).

Pull request added by hand since that was simpler.
