### ISSUE TITLE
meta message length inconsistency

### ISSUE THREAD

**Issue by dliw** [craigsapp/midifile#40]
There are two ways to create meta messages using either [MidiFile](https://github.com/craigsapp/midifile/blob/master/src-library/MidiFile.cpp#L1377) or [MidiMessage](https://github.com/craigsapp/midifile/blob/master/src-library/MidiMessage.cpp#L1346).
The latter however does not use a VLV for the data length and the generated meta messages differ.

Furthermore `MidiFile::write` already adds the VLV length [automatically](https://github.com/craigsapp/midifile/blob/master/src-library/MidiFile.cpp#L602) for some messages, so it can be omitted when creating specific messages.

I think this would be useful for meta messages as well. The VLV length is really only needed for reading / writing MIDI files. When working with the data `vector<uchar>` contains all the information needed.

One more thing (not worth a separate issue): There is a typo in ["until"](https://github.com/craigsapp/midifile/blob/master/src-library/MidiFile.cpp#L1197)...

**Comment by craigsapp** [comment]
Yes, I did not deal with the VLV aspect of meta-message lengths until this week...

Meta-messages should now be able to be read/write using VLV numbers up to at least 4 bytes long (I allow for some cases to be up to 5 bytes but still need to debug and test such cases, and probably review the MIDI spec for very large VLVs).

> Furthermore MidiFile::write already adds the VLV length automatically for some messages, so it can be omitted when creating specific messages.

`MidiFile::write` automatically converts tick delta times into VLV values for the MIDI event timestamps.  So `MidEvent::tick` is always in an uncompressed form representing the ticks as an integer (rather than VLV).  One reason is that the `MidiFile` class also unpacks the delta ticks into absolute ticks by default.  So typically the `MidiEvent::tick` value does not directly represent the delta timestamp within the MIDI file (i.e., it is at a higher conceptual level than the values stored in the MIDI file).

The size of meta-messages is a different category of VLV, which are handled differently.  The `MidiMessage` class is fairly low-level, consisting of the raw bytes in a `vector<uchar>` inherited object.  I could remove such VLVs from the data, but this would break the code in several places, and would force the data structure to be a higher-level concept.  Instead I have added two functions to access the data at a higher level of abstraction without having the programmer to deal with the VLV data size in the message:

(1) `MidiMessage::getMetaContent()`

https://github.com/craigsapp/midifile/blob/00d29084dbec0dcf071206bed6053041c7da3fb1/src-library/MidiMessage.cpp#L1315-L1345

Use this function to extract the data of the meta message.   This function detects the width of the VLV size and skips over it to copy the contents of the actual data content of the meta message.

(2) `MidiMessage::setMetaContent()`

https://github.com/craigsapp/midifile/blob/00d29084dbec0dcf071206bed6053041c7da3fb1/src-library/MidiMessage.cpp#L1349-L1401

This function sets the meta-message data content and also calculate the VLV data size to insert in the message after the meta-message type byte.

With these two functions added, the problem of the VLV being stored in the meta message content is no longer a hassle.


> One more thing (not worth a separate issue): There is a typo in "until"...

Thanks, fixed in commit https://github.com/craigsapp/midifile/commit/00d29084dbec0dcf071206bed6053041c7da3fb1
