### ISSUE TITLE
Meta event parse error

### ISSUE THREAD

**Issue by FlyingFishBird** [craigsapp/midifile#45]
The structure of  Meta event is:
**`0xFF <type byte> <var len> data ...`**
and in MidiFile.cpp line 2599:
```C             
metai = MidiFile::readByte(input); // meta type
array.push_back(metai);
for (uchar j=0; j<metai; j++) {
    byte = MidiFile::readByte(input); // meta type
    array.push_back(byte);
}
```
use 1 byte  **metai** as the **var len**.

If a mid file contains a meta event which is larger than 127 bytes
etc: I will save a custom text event to track who play this song in my app.
This file will read failed.

**Comment by FlyingFishBird** [comment]
**How to fix:**
Replace line 2599 - 2564 to
```C
               int length = (int)readVLValue(input);
               for (i=0; i<length; i++) {
                  byte = MidiFile::readByte(input);
                  array.push_back(byte);
               }
```

**Comment by FlyingFishBird** [comment]
To look up a meta event's detail, visit: https://www.csie.ntu.edu.tw/~r92092/ref/midi/

**Comment by craigsapp** [comment]
Thanks!  I had not yet considered meta-messages larger than 127 bytes, but they are allowed according to the standard MIDI file specification, and the data size is stored as a variable length value as you mention.

Commit https://github.com/craigsapp/midifile/commit/99bf5e42b726f00d18ad47a6dc88b21172e7852d implements a fix to allow for reading meta-messages larger than 127 bytes.


Here is some test data with a 300-byte text meta message:

```

"MThd"
4'6
2'0
2'1
2'100

"MTrk"
4'309
v0 FF 01 v300
	"ABCDEFGHIJKLMNOPQRSTUVWXY" "abcdefghijklmnopqrstuvwxy"
	"ABCDEFGHIJKLMNOPQRSTUVWXY" "abcdefghijklmnopqrstuvwxy"
	"ABCDEFGHIJKLMNOPQRSTUVWXY" "abcdefghijklmnopqrstuvwxy"
	"ABCDEFGHIJKLMNOPQRSTUVWXY" "abcdefghijklmnopqrstuvwxy"
	"ABCDEFGHIJKLMNOPQRSTUVWXY" "abcdefghijklmnopqrstuvwxy"
	"ABCDEFGHIJKLMNOPQRSTUVWXY" "abcdefghijklmnopqrstuvwxy"
v0 FF 2F 00
```

or as hex byte codes:

```
4d 54 68 64 00 00 00 06 00 00 00 01 00 64 4d 54 72 6b 00 00 01 35 00 ff 01 
82 2c 41 42 43 44 45 46 47 48 49 4a 4b 4c 4d 4e 4f 50 51 52 53 54 55 56 57 
58 59 61 62 63 64 65 66 67 68 69 6a 6b 6c 6d 6e 6f 70 71 72 73 74 75 76 77 
78 79 41 42 43 44 45 46 47 48 49 4a 4b 4c 4d 4e 4f 50 51 52 53 54 55 56 57 
58 59 61 62 63 64 65 66 67 68 69 6a 6b 6c 6d 6e 6f 70 71 72 73 74 75 76 77 
78 79 41 42 43 44 45 46 47 48 49 4a 4b 4c 4d 4e 4f 50 51 52 53 54 55 56 57 
58 59 61 62 63 64 65 66 67 68 69 6a 6b 6c 6d 6e 6f 70 71 72 73 74 75 76 77 
78 79 41 42 43 44 45 46 47 48 49 4a 4b 4c 4d 4e 4f 50 51 52 53 54 55 56 57 
58 59 61 62 63 64 65 66 67 68 69 6a 6b 6c 6d 6e 6f 70 71 72 73 74 75 76 77 
78 79 41 42 43 44 45 46 47 48 49 4a 4b 4c 4d 4e 4f 50 51 52 53 54 55 56 57 
58 59 61 62 63 64 65 66 67 68 69 6a 6b 6c 6d 6e 6f 70 71 72 73 74 75 76 77 
78 79 41 42 43 44 45 46 47 48 49 4a 4b 4c 4d 4e 4f 50 51 52 53 54 55 56 57 
58 59 61 62 63 64 65 66 67 68 69 6a 6b 6c 6d 6e 6f 70 71 72 73 74 75 76 77 
78 79 00 ff 2f 00 
```

This data will be read correctly by `src-programs/readstatus.cpp` for example.

---------

I could not directly implement your solution:

```cpp
               int length = (int)readVLValue(input);
               for (i=0; i<length; i++) {
                  byte = MidiFile::readByte(input);
                  array.push_back(byte);
               }
```

because the `MidiMessage` class stores data at a lower level, and the data size must also be stored in the message byte arrray, and the size must be stored as a VLV.  

In commit https://github.com/craigsapp/midifile/commit/36260e52577569e8e26138dcd7dcac2d96983d5f I and some other commit, I added `MidiMessage::getMetaContent()` and `MidiMessage::setMetaContent()`.  These functions automatically handle the data size variable (even if multibyte VLV) to extract the meta data content as a string.

For example, to read the content of a text meta-message would be something like:

```cpp
    MidiFile midifile;
    midifile.read("myfile.mid");
    for (int i=0; i<midifile[0].size(); i++) {
         if (midifile[0][i].isText()) {
            string text = midifile[0][i]->getMetaContent();
            cout << "TEXT = " << text << endl;
         }
    }
```

A current limitation is that the size of a meta message cannot exceed 2^28-1 (268 MB) rather than the full 2GB or 4GB that VLV values would allow.
