### ISSUE TITLE
How to copy tempo track,key track,and meter track from one midifile to an empty midifile?

### ISSUE THREAD

**Issue by zhanima** [craigsapp/midifile#65]
![1](https://user-images.githubusercontent.com/47018362/56600245-d6357d00-662a-11e9-9694-0194e4641fb1.PNG)
I use MUSICSTD to check midifiles ,from it i can see three tracks that store tempo,key,and meter. However i'm not sure whether there were 3 tracks that actually exist in midifile or it was just one track that contains all 3 kinds of data.I tried to use the following code to do the function but it failed.

```cpp
	MidiFile midifile_changed;
	midifile_changed.addTrack();
	for (int j = 0; j<midifile[0].getEventCount(); j++)
		midifile_changed.addEvent(midifile[0][j]);
	midifile_changed.addTrack();
	for (int j = 0; j<midifile[1].getEventCount(); j++)
		midifile_changed.addEvent(midifile[1][j]);
```

When I only copy track[0],the tempo track dosen't exist in MUSICSTD .
And when I copy both these two tracks,the tempo track exist,but sometimes it copys the sound track of the original midifile. 
Not sure how to do now...

**Comment by zhanima** [comment]
Is it that some of the midi contains mutiple tracks that store these 3 kinds of data and some of it only has one or even none?

**Comment by craigsapp** [comment]
`midifile_changed` starts with one track (track[0]) when it is created:

```cpp
	MidiFile midifile_changed;
```

The following line adds another track to `midifile_changed`, so there are now two tracks in it:

```cpp
	midifile_changed.addTrack();
```

Then the for-loop copies the contents of `midifile[0]` to `midifile_changed[0]`.  Note that it is not copied into `midifile_changed[1]` because the track assignment is taken from the track of the event in `midifile[0][j]`.

```cpp
	for (int j = 0; j<midifile[0].getEventCount(); j++)
		midifile_changed.addEvent(midifile[0][j]);
```

You may intend to copy into `midifile_changed[1]` which can be done like this:

```cpp
	for (int j = 0; j<midifile[0].getEventCount(); j++)
		midifile_changed.addEvent(1, midifile[0][j]);
```

or

```cpp
	for (int j = 0; j<midifile[0].getEventCount(); j++)
		midifile_changed[1].append(midifile[0][j]);
```

The following code creates a third track in `midifile_changed`, and then copies the contents of `midifile[1]` into `midifile_changed[1]`. (but `midifile_changed[2]` will remain empty.

```cpp
	midifile_changed.addTrack();
	for (int j = 0; j<midifile[1].getEventCount(); j++)
		midifile_changed.addEvent(midifile[1][j]);
```

The difference between `midifile` and `midifile_changed` in your code is that `midifile_changed` contains a copy of the first two tracks of `midifile`, and then also has an empty third track.    You would also need to check that `midifile` has at least two tracks (there will be a problem if `midifile` has only one track.

**Comment by craigsapp** [comment]
> Is it that some of the midi contains mutiple tracks that store these 3 kinds of data and some of it only has one or even none?

There are two general types of MIDI files.  

The first is called "Type-0":  This MIDI file contains a single track which contains all notes, tempo, meter, key signature and other sorts of messsages.

The second type of MIDI file is called "Type-1": This MIDI file contains more than one track.  The first track is used to store tempo messages and other similar items that are common to all other tracks.  The first track should not contain notes, and is often called an "expression track" or "tempo track".  The rest of the tracks contain notes, control messages.  Typically each track is used to store the notes for a particular instrument, but that is not a requirement.

Having a separate "meter track" and a "key track" is not standard, although it is possible.
