### ISSUE TITLE
This if else statement makes no sense

### ISSUE THREAD

**Issue by rettinghaus** [craigsapp/midifile#75]
https://github.com/craigsapp/midifile/blob/d1c2139083d1386db55860d29eac14b11a95a9c8/src/MidiFile.cpp#L441-L449

**Comment by craigsapp** [comment]
That is the appendix of the MidiFile class 😜 

Contextually, line 441 should have been:

```cpp
     if (bytes[0] != 0xff && bytes[1] != 0xf0) {
```

Where `0xf0` is a system-exclusive message.  It looks like I was planning on doing something special to system exclusive messages (who knows what that was), but I never did.

Fixed with commit https://github.com/craigsapp/midifile/commit/6c5aca0277e9ae17dabfab60fd60d2b3f5a3fe5c

There was also some abandoned null termination for text strings (only raw bytes without null terminations are now stored, and there are accessor functions to pull out text contents).
