### ISSUE TITLE
Unreachable code

### ISSUE THREAD

**Issue by rettinghaus** [craigsapp/midifile#76]
https://github.com/craigsapp/midifile/blob/d1c2139083d1386db55860d29eac14b11a95a9c8/src/Binasc.cpp#L781

**Comment by craigsapp** [comment]
Did a compiler give a warning about that?  If so I will comment the line out; otherwise, I almost always put breaks after each case in a switch whether it is actually needed or not.  This is because if I were to remove the `return` statement, the case would still break properly and not proceed accidentally to the next case.

**Comment by rettinghaus** [comment]
Ok.
