### ISSUE TITLE
Infinite loop 

### ISSUE THREAD

**Issue by vmstarchenko** [craigsapp/midifile#79]
While reading a particular type of files, the library enters the infinite loop. The problem can be reproduced with a file consisting of 1025 or more null symbols. In order to get the minimal example, call `python -c "with open('data.mid', 'wb') as f: f.write('\x00' * 1025)"` and then open it with `main.cpp` as `Midifile("data.mid")`.

It happens in the following loop:
https://github.com/craigsapp/midifile/blob/master/src/Binasc.cpp#L270
The problem occurs when `getline` reads an empty string. The file cursor does not move, and `eof` never gets reached.

I am not sure what behavior is supposed in the midi-format but it seems that one could just include `&& inputLine[0] != '\0'` into the condition of the cycle.

My main problem  now is that I can't validate input file because the infinite loop occurs before I have any ability to check `status`.

**Comment by craigsapp** [comment]
This is caused in `MidiFile::read(istream&)` by first checking if the file is a Standard MIDI file, and if not, then read as an ASCII-encoded MIDI file:

https://github.com/craigsapp/midifile/blob/6c5aca0277e9ae17dabfab60fd60d2b3f5a3fe5c/src/MidiFile.cpp#L175-L192

The best solution will be to fail gracefully at the first non-printable character found when attempting to read the file in an ASCII format.  There may be a new problem generated: if accented characters are used.  But someone can submit a report if they want UTF-8/16 (or other character sets) files to be read (or they can encode the "non-printable" bytes as hex byte codes in such cases).

If the input is a text file with only printable characters, then there could be strange parsing behavior.  Another possibility would be to implement `MidiFile::readSmf()` which does not attempt to parse files that do not start with the letter `M` as ASCII-encoded MIDI files.

I have rarely also seen [RIFF](https://en.wikipedia.org/wiki/Resource_Interchange_File_Format)-encoded MIDI files, which I have never bothered to deal with.

I want to implement import of [Base64](https://github.com/craigsapp/midifile/issues/85)-encoded MIDI files, where it might be nice to have a related `MidiFile::readBase64()` function (and it will also be more difficult to automatically identify base64 data, since it could theoretically start with the characters `MThd` just as a Standard MIDI File does.

**Comment by craigsapp** [comment]
The `MidiFile::readSmf()` function is implemented in commit https://github.com/craigsapp/midifile/commit/d6906d87a4e5d9d9c6d99d1159355b358eb7028a

This is one solution to the issue, where only Standard MIDI Files are allowed as input (and it should filter out most other input except perhaps corrupted MIDI files).

I will also implement the non-printable solution, which should also fix your problem.

**Comment by craigsapp** [comment]
Fixed with commit https://github.com/craigsapp/midifile/commit/e063d474d4fd027400b2bc308820a9e61f7679ab

The problem was `std::istream::getline()` (using `char[]` array for storing input).  I changed it to `std::getline()` (using `std::string for storing input) which fixed the problem when reading data that only contains null characters.
